#!/usr/bin/env bash
#
# Autonomy Witness — bounded, docs-only PR opener.
#
# Invoked only by .github/workflows/autonomy-witness.yml (manual dispatch). It
# opens a docs-only pull request authored by the allowlisted autonomous identity
# github-actions[bot], to prove that identity can pass branch protection. Every
# bound here is asserted by:
#   - .github/scripts/tests/autonomy-witness-workflow.test.mjs   (static policy)
#   - .github/scripts/tests/autonomy-witness-behavior.test.mjs   (runtime behavior)
#
# Required env (all trusted GitHub-provided values; there are NO workflow inputs,
# so nothing user-supplied can reach a ref, path, or command):
#   GH_TOKEN        built-in GITHUB_TOKEN (no secrets / PAT / App key)
#   RUN_ID          github.run_id (integer)
#   HEAD_SHA        github.sha
#   REPO            owner/repo
#   DEFAULT_BRANCH  repository default branch
set -euo pipefail

: "${GH_TOKEN:?GH_TOKEN required}"
: "${RUN_ID:?RUN_ID required}"
: "${HEAD_SHA:?HEAD_SHA required}"
: "${REPO:?REPO required}"
: "${DEFAULT_BRANCH:?DEFAULT_BRANCH required}"

# RUN_ID is a GitHub-assigned integer. Enforcing that keeps the fixed branch
# prefix and docs path from ever being steered to an arbitrary ref or path.
if [[ ! "$RUN_ID" =~ ^[0-9]+$ ]]; then
  echo "ERROR: RUN_ID must be a positive integer." >&2
  exit 1
fi

BRANCH="autonomy-witness/${RUN_ID}"
DOC_DIR="doc/autonomy-witness"
DOC_PATH="${DOC_DIR}/${RUN_ID}.md"
OWNER="${REPO%%/*}"

# Allowlisted autonomous identity. Only GH_TOKEN (GITHUB_TOKEN) is used, so the
# resulting PR is authored by github-actions[bot].
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# Re-run safe: if the run-id branch already exists on origin, continue FROM it so
# an unchanged re-run is a genuine no-op. Only ever the fixed run-id branch is
# fetched (a literal refspec, never an arbitrary ref). Otherwise start from the
# already-checked-out default branch.
if git ls-remote --exit-code --heads origin "refs/heads/${BRANCH}" >/dev/null 2>&1; then
  git fetch --no-tags --depth=1 origin "+refs/heads/${BRANCH}:refs/remotes/origin/${BRANCH}"
  git checkout -B "$BRANCH" "refs/remotes/origin/${BRANCH}"
else
  git checkout -B "$BRANCH"
fi

mkdir -p "$DOC_DIR"

# Deterministic content derived only from trusted run metadata, so an unchanged
# re-run reproduces byte-identical output.
{
  printf '# Autonomy witness — run %s\n\n' "$RUN_ID"
  printf 'Generated by the Autonomy Witness workflow to prove that the\n'
  printf 'allowlisted autonomous identity github-actions[bot] can open a\n'
  printf 'green, docs-only pull request through branch-protected checks.\n\n'
  printf -- '- Run ID: %s\n' "$RUN_ID"
  printf -- '- Source commit: %s\n' "$HEAD_SHA"
  printf -- '- Branch: %s\n\n' "$BRANCH"
  printf 'Disposable witness output. Cleanup: close the associated PR and\n'
  printf 'delete branch %s; this file may then be removed.\n' "$BRANCH"
} > "$DOC_PATH"

git add "$DOC_PATH"

# Because we resumed from the existing branch tip (when present), an unchanged
# run leaves the index identical to HEAD → no new commit.
if git diff --cached --quiet; then
  echo "No changes to commit (idempotent re-run)."
else
  git commit -m "docs(autonomy-witness): witness run ${RUN_ID}"
fi

# Fast-forward push: the branch is either brand new or advanced from its own tip,
# so no force is needed — a divergent remote is surfaced rather than clobbered.
git push origin "$BRANCH"

# Re-run safe AND SIGPIPE-safe: select the first open PR for this branch that is
# owned by THIS repo (never a same-named fork branch) entirely inside jq. There
# is no `head`/early-terminating consumer, so `gh pr list` cannot take SIGPIPE
# under `set -o pipefail`.
existing="$(gh pr list --repo "$REPO" --state open --head "$BRANCH" \
  --json number,headRepositoryOwner \
  --jq "[.[] | select(.headRepositoryOwner.login == \"${OWNER}\") | .number] | first // empty")"

if [ -n "$existing" ]; then
  echo "Reusing existing witness PR #${existing}"
  gh pr view "$existing" --repo "$REPO" --json url --jq .url
  exit 0
fi

gh pr create --repo "$REPO" --base "$DEFAULT_BRANCH" --head "$BRANCH" \
  --title "docs(autonomy-witness): witness run ${RUN_ID}" \
  --body "Permanent operational witness infrastructure. This docs-only PR was opened by the allowlisted autonomous identity github-actions[bot] to validate that autonomous identity can open a green PR through branch protection. It changes only doc/autonomy-witness/${RUN_ID}.md. Do NOT auto-merge or auto-approve. Cleanup: close this PR and delete branch ${BRANCH} after witnessing."
