#!/usr/bin/env bash
#
# Autonomy Witness — bounded, docs-only PR opener.
#
# Invoked only by .github/workflows/autonomy-witness.yml (manual dispatch). It
# opens a docs-only pull request authored by an allowlisted autonomous App
# identity, to prove that identity can pass branch protection. Every bound here
# is asserted by:
#   - .github/scripts/tests/autonomy-witness-workflow.test.mjs   (static policy)
#   - .github/scripts/tests/autonomy-witness-behavior.test.mjs   (runtime behavior)
#
# Event-trigger note: GH_TOKEN MUST be a GitHub App installation token, NOT the
# built-in GITHUB_TOKEN. GitHub suppresses pull_request/pull_request_target/push
# workflow triggers for events created with GITHUB_TOKEN, so a witness opened
# with it would author a github-actions[bot] PR on which NO required checks ever
# run. `gh pr create` uses GH_TOKEN, so opening the PR with an App token makes the
# normal PR workflows fire. The branch push relies on the ambient checkout
# credential (GITHUB_TOKEN), which is fine because push events are not required.
#
# Required env (all trusted GitHub-provided values; there are NO workflow inputs,
# so nothing user-supplied can reach a ref, path, or command):
#   GH_TOKEN        commitperclip App installation token (see note above); used
#                   only by `gh`. NEVER the built-in GITHUB_TOKEN.
#   RUN_ID          github.run_id (integer)
#   HEAD_SHA        github.sha
#   REPO            owner/repo
#   DEFAULT_BRANCH  repository default branch
set -euo pipefail

# The witness must be authored by the allowlisted commitperclip App identity. A
# positive allowlist (rather than merely excluding github-actions[bot]) also
# catches a misconfigured App or a wrong installation. In particular a
# github-actions[bot] author means the PR was created with the built-in
# GITHUB_TOKEN, whose pull_request workflows are suppressed → the required checks
# never ran, so a check-less witness could otherwise masquerade as valid.
EXPECTED_AUTHOR="commitperclip[bot]"

: "${GH_TOKEN:?GH_TOKEN required}"
: "${RUN_ID:?RUN_ID required}"
: "${HEAD_SHA:?HEAD_SHA required}"
: "${REPO:?REPO required}"
: "${DEFAULT_BRANCH:?DEFAULT_BRANCH required}"

# RUN_ID is a GitHub-assigned integer. Enforcing that keeps the fixed branch
# prefix and docs path from ever being steered to an arbitrary ref or path.
if [[ ! "$RUN_ID" =~ ^[0-9]+$ ]]; then
  echo "ERROR: RUN_ID must be a positive integer." >&2
  exit 1
fi

BRANCH="autonomy-witness/${RUN_ID}"
DOC_DIR="doc/autonomy-witness"
DOC_PATH="${DOC_DIR}/${RUN_ID}.md"
OWNER="${REPO%%/*}"

# Commit identity for the docs commit (pushed with the ambient checkout token).
# The PR *author* — the identity the autonomy allowlist and paperclip-checker
# actually evaluate — is instead set by GH_TOKEN (the App installation token)
# when `gh pr create` runs below.
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# Re-run safe: if the run-id branch already exists on origin, continue FROM it so
# an unchanged re-run is a genuine no-op. Only ever the fixed run-id branch is
# fetched (a literal refspec, never an arbitrary ref). Otherwise start from the
# already-checked-out default branch.
if git ls-remote --exit-code --heads origin "refs/heads/${BRANCH}" >/dev/null 2>&1; then
  git fetch --no-tags --depth=1 origin "+refs/heads/${BRANCH}:refs/remotes/origin/${BRANCH}"
  git checkout -B "$BRANCH" "refs/remotes/origin/${BRANCH}"
else
  git checkout -B "$BRANCH"
fi

mkdir -p "$DOC_DIR"

# Deterministic content derived only from trusted run metadata, so an unchanged
# re-run reproduces byte-identical output.
{
  printf '# Autonomy witness — run %s\n\n' "$RUN_ID"
  printf 'Generated by the Autonomy Witness workflow to prove that an\n'
  printf 'allowlisted autonomous App identity can open a green, docs-only\n'
  printf 'pull request through branch-protected checks (opened with an App\n'
  printf 'installation token so the required PR workflows actually run).\n\n'
  printf -- '- Run ID: %s\n' "$RUN_ID"
  printf -- '- Source commit: %s\n' "$HEAD_SHA"
  printf -- '- Branch: %s\n\n' "$BRANCH"
  printf 'Disposable witness output. Cleanup: close the associated PR and\n'
  printf 'delete branch %s; this file may then be removed.\n' "$BRANCH"
} > "$DOC_PATH"

git add "$DOC_PATH"

# Because we resumed from the existing branch tip (when present), an unchanged
# run leaves the index identical to HEAD → no new commit.
if git diff --cached --quiet; then
  echo "No changes to commit (idempotent re-run)."
else
  git commit -m "docs(autonomy-witness): witness run ${RUN_ID}"
fi

# Fast-forward push: the branch is either brand new or advanced from its own tip,
# so no force is needed — a divergent remote is surfaced rather than clobbered.
git push origin "$BRANCH"

# Re-run safe AND SIGPIPE-safe: select the first open PR for this branch that is
# owned by THIS repo (never a same-named fork branch) entirely inside jq. There
# is no `head`/early-terminating consumer, so `gh pr list` cannot take SIGPIPE
# under `set -o pipefail`.
resolve_pr_number() {
  gh pr list --repo "$REPO" --state open --head "$BRANCH" \
    --json number,headRepositoryOwner \
    --jq "[.[] | select(.headRepositoryOwner.login == \"${OWNER}\") | .number] | first // empty"
}

pr_number="$(resolve_pr_number)"

if [ -n "$pr_number" ]; then
  echo "Reusing existing witness PR #${pr_number}"
else
  gh pr create --repo "$REPO" --base "$DEFAULT_BRANCH" --head "$BRANCH" \
    --title "docs(autonomy-witness): witness run ${RUN_ID}" \
    --body "Permanent operational witness infrastructure. This docs-only PR was opened by an allowlisted autonomous App identity, using an App installation token (NOT the built-in GITHUB_TOKEN) so the required PR workflows actually run on the exact head. It validates that autonomous identity can open a green PR through branch protection. It changes only doc/autonomy-witness/${RUN_ID}.md. Do NOT auto-merge or auto-approve. Cleanup: close this PR and delete branch ${BRANCH} after witnessing."
  pr_number="$(resolve_pr_number)"
  if [ -z "$pr_number" ]; then
    echo "ERROR: could not resolve the witness PR number after creation." >&2
    exit 1
  fi
fi

# Fail closed unless the PR is authored by the expected allowlisted App identity.
# A positive allowlist rejects not only the github-actions[bot] event-suppression
# signature (built-in GITHUB_TOKEN → suppressed pull_request workflows → no
# required checks) but also any misconfigured App or wrong installation. Applies
# whether the PR was freshly created or reused.
author="$(gh pr view "$pr_number" --repo "$REPO" --json author --jq .author.login)"
if [ "$author" != "$EXPECTED_AUTHOR" ]; then
  echo "ERROR: witness PR #${pr_number} is authored by '${author}', not the allowlisted App identity '${EXPECTED_AUTHOR}'. In particular github-actions[bot] is produced only by the built-in GITHUB_TOKEN, whose pull_request workflows are suppressed so the required checks never run. Open the witness with a minted commitperclip App installation token instead." >&2
  exit 1
fi

echo "Witness PR #${pr_number} authored by ${author} (App/bot identity; required PR workflows will run on the exact head)."
gh pr view "$pr_number" --repo "$REPO" --json url --jq .url
